### PR TITLE
Some mostly cosmetic changes to get started

### PR DESCRIPTION
**Pull request by taliesin**
All but the last commit are pretty cosmetic and hopefully fit the overall style.

The helper timeout functions (last commit) try to reduce complexity a bit and there was one situation that seems like a bug, so a TODO was inserted. Please review this situation.

### CODE REVIEW

**Comment by taliesin** [comment]
This still says 'merging is blocked', but all commits were signed off?
Not sure what I'm doing wrong.

**Comment by dzurikmiroslav** [comment]
The `main` branch has set _Require signed commits_, I turned it off and now is merge applicable...

**Comment by dzurikmiroslav** [comment]
Merged, thanks for the code review :-)

**Comment by taliesin** [comment]
Could you please reflect on the TODO in the last commit, I've marked it with a comment.

**Comment by dzurikmiroslav** [comment]
When the wallbox requires authorization to start charging. EV can be authorized before connecting to the wallbox.
By authorizing (clicking the Authorize button or sending a Modbus command, etc.), authorization is enabled for 60 seconds for the first connected EV. If the EV is disconnected within 30 seconds and another EV is connected immediately, it must be authorized again.

Therefore, _auth_grant_to_ is always set to 0, not just when it is expired.

I know that 60 seconds is not much for replacing the EV, but I was thinking about the fact that it could also be a configurable parameter.

**Comment by taliesin** [comment]
so I would say:

```
authorized = is_expired(&auth_grant_to);
// in any case we need a fresh authorization, if the EV is disconnected.
auth_grant_to = 0;
```
... would be a correct solution and be more descriptive.

**Comment by dzurikmiroslav** [comment]
Yes, that should works currently

**Comment by dzurikmiroslav** [comment]
So, when I wrote some unit tests, I found out the check `authorized = is_expired(&auth_grant_to);` not work correctly. First time when EV was not authorized it always return true. The problem was non zero value check in `is_expired`.
After reverting to `authorized = auth_grant_to >= xTaskGetTickCount();` authorizing work correctly.

**Comment by taliesin** [comment]
I'm currently too busy to work on it, but the revert somehow defies the change to is_expired(). My impression is that auth_grant_to should be initialized, so that is_expired() works.

**Pull request merged**
